data_config:
    file_list_fn: '/home/jsevillamol/Documentos/datasample/sample_files.txt'
    channels: ['image_charge','image_peak_times']
    img_size: [108, 108]
    selected_tel_types: ['LST', 'MSTF']
    image_mapping_config:
        hex_conversion_algorithm: 'oversampling'
    preprocessing_config:
        normalization: 'log_normalization'
        resize_mode: 'interpolate'
        event_order: null
        sequence_padding: 'post'

train_config:
    epochs: 1
    batch_size: 32
    val_split: 0.2
    seed: 1111
    shuffle: true

    train_dir: '/home/jsevillamol/Documentos/output/'


